### ISSUE TITLE
Add more trees to the list

### ISSUE THREAD

**Issue by Franqsanz** [Franqsanz/fruits-api#15]
Add more fruit trees to the file [`src/data/data.js`](https://github.com/Franqsanz/fruits-api/blob/main/src/data/data.js), this file contains an array of objects.

Example of what it looks like and what you should add:

```js
{
  id: "<number>",
  scientific_name: "<scientific name>",
  tree_name: "<tree name>",
  fruit_name: "<fruit name>",
  family: "<family>",
  origin: "<origen>",
  description: "<a short description>",
  bloom: "<flowering time>",
  maturation_fruit: "<ripening time>",
  life_cycle: "<approximate years of life>",
  climatic_zone: "<climatic zone>",
  producing_countries: [
   {
    country: "<country name>",
   },
   //...
  ]
},
```
⚠ **Important**
Check if the tree already exists, put the name starting with capital letters.

**Comment by rjrishika** [comment]
i want to contribute on this issue can you assign me I am new in open source

**Comment by Franqsanz** [comment]
Hello, @rjrishika welcome, happy contribution!

**Comment by Ishukumarpathak** [comment]
Hey, I want to work in this, can you please assign me the same …

**Comment by jatin41** [comment]
i want to contribute

**Comment by Franqsanz** [comment]
Hello, welcome, check well that there are no repeated trees.
