### ISSUE TITLE
Agregar compatibilidad con Docker (Add Docker support)

### ISSUE THREAD

**Issue by cmjchrisjones** [Franqsanz/fruits-api#16]
La capacidad de ejecutar el proyecto dentro de un contenedor docker para que Node/NPM no sea un requisito previo y tenga un entorno de desarrollo aislado. El único requisito previo que se requeriría sería Docker.

[blog](https://auth0.com/blog/use-docker-to-create-a-node-development-environment/) con más información sobre los beneficios de usar Docker

-----------------------------

The ability to run the project inside a docker container so that Node/NPM isn't required as a pre-requisite, and you have an isolated development environment. The only pre-requisite that would be required would be Docker.

[blog](https://auth0.com/blog/use-docker-to-create-a-node-development-environment/) with more information about the benefits of using Docker

**Comment by Franqsanz** [comment]
Hi, thanks for your contribution, I'll take a look.
