### ISSUE TITLE
Create a version of the README translated into English

### ISSUE THREAD

**Issue by Franqsanz** [Franqsanz/fruits-api#22]
Add a new English translated README file.

**Comment by Carababusha** [comment]
Hi @Franqsanz!

I can help with this if you want :)

**Comment by PaolaDaft** [comment]
Hola, Una forma en especifico de como quieres que se implemente esta nueva documentación?

**Comment by Franqsanz** [comment]
Hi @Carababusha cool, welcome and thanks for the help.

**Comment by Franqsanz** [comment]
Hola @PaolaDaft, solo quiero una versión en inglés, con la misma implementación. Gracias
